version: '3.8'

services:
  mongo1:
    image: mongo:5.0.14
    container_name: mongo1
    environment:
      MONGO_INITDB_ROOT_USERNAME: rs
      MONGO_INITDB_ROOT_PASSWORD: rs
    ports:
      - "27017:27017"
    networks:
      - mongo-cluster
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--keyFile", "/data/configdb/mongo-keyfile", "--auth"]
    volumes:
      - ./init-replica-set.js:/docker-entrypoint-initdb.d/init-replica-set.js
      - ./mongo-keyfile:/data/configdb/mongo-keyfile
      - mongo1_data:/data/db

  mongo2:
    image: mongo:5.0.14
    container_name: mongo2
    environment:
      MONGO_INITDB_ROOT_USERNAME: rs
      MONGO_INITDB_ROOT_PASSWORD: rs
    ports:
      - "27018:27017"
    networks:
      - mongo-cluster
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--keyFile", "/data/configdb/mongo-keyfile", "--auth"]
    volumes:
      - ./init-replica-set.js:/docker-entrypoint-initdb.d/init-replica-set.js
      - ./mongo-keyfile:/data/configdb/mongo-keyfile
      - mongo2_data:/data/db

  mongo3:
    image: mongo:5.0.14
    container_name: mongo3
    environment:
      MONGO_INITDB_ROOT_USERNAME: rs
      MONGO_INITDB_ROOT_PASSWORD: rs
    ports:
      - "27019:27017"
    networks:
      - mongo-cluster
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--keyFile", "/data/configdb/mongo-keyfile", "--auth"]
    volumes:
      - ./init-replica-set.js:/docker-entrypoint-initdb.d/init-replica-set.js
      - ./mongo-keyfile:/data/configdb/mongo-keyfile
      - mongo3_data:/data/db

networks:
  mongo-cluster:
    driver: bridge

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
